services:
  - type: web
    name: steam-api
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: steam-db
          property: connectionString
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_REFRESH_SECRET_KEY
        generateValue: true

databases:
  - name: steam-db
    databaseName: steam_database
    user: steam_user
    plan: free
